=== xtump/games/xsd.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="games">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="game" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="title"/>
              <xs:element type="xs:string" name="studio"/>
              <xs:element type="xs:string" name="web"/>
              <xs:element name="user">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="email"/>
                    <xs:element name="psw">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="stars" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="xs:string" name="server"/>
                    <xs:element name="settings">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="general">
                            <xs:complexType>
                              <xs:sequence>
                                  <xs:element  name="spam"><xs:simpleType> <xs:restriction base="xs:string">  <xs:enumeration value="Show"/> <xs:enumeration value="Hide"/> </xs:restriction> </xs:simpleType> </xs:element>
                                  <xs:element  name="add_friend"><xs:simpleType> <xs:restriction base="xs:string"> <xs:enumeration value="auto"/> <xs:enumeration value="ask"/> </xs:restriction> </xs:simpleType> </xs:element>
                                <xs:element  name="battle_types"/>
                                <xs:element name="battle_save">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute type="xs:string" name="source" use="optional"/>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element type="xs:string" name="advanced_scoope"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="graphics">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element type="xs:string" name="resolution"/>
                                <xs:element type="xs:string" name="mode"/>
                                <xs:element name="gamma">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute type="xs:byte" name="value" use="optional"/>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="brightness">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute type="xs:byte" name="value" use="optional"/>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="colorblind_mode">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute type="xs:string" name="enabled" use="optional"/>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="vertical_sync">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute type="xs:string" name="enabled" use="optional"/>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="triple_buff">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute type="xs:string" name="enabled" use="optional"/>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element  name="texture_quality"><xs:simpleType> <xs:restriction base="xs:string"> <xs:enumeration value="Low"/> <xs:enumeration value="Medium"/> <xs:enumeration value="High"/> </xs:restriction> </xs:simpleType></xs:element>
                                <xs:element  name="shadow_quality"><xs:simpleType> <xs:restriction base="xs:string"> <xs:enumeration value="Low"/> <xs:enumeration value="Medium"/> <xs:enumeration value="High"/> </xs:restriction> </xs:simpleType></xs:element>
                                <xs:element  name="terrain_quality"><xs:simpleType> <xs:restriction base="xs:string"> <xs:enumeration value="Low"/> <xs:enumeration value="Medium"/> <xs:enumeration value="High"/> </xs:restriction> </xs:simpleType></xs:element>
                                <xs:element  name="water_quality"><xs:simpleType> <xs:restriction base="xs:string"> <xs:enumeration value="Low"/> <xs:enumeration value="Medium"/> <xs:enumeration value="High"/> </xs:restriction> </xs:simpleType></xs:element>
                                <xs:element  name="post_processing"><xs:simpleType> <xs:restriction base="xs:string"> <xs:enumeration value="Low"/> <xs:enumeration value="Medium"/> <xs:enumeration value="High"/> </xs:restriction> </xs:simpleType></xs:element>
                                <xs:element  name="foliage_quality"><xs:simpleType> <xs:restriction base="xs:string"> <xs:enumeration value="Low"/> <xs:enumeration value="Medium"/> <xs:enumeration value="High"/> </xs:restriction> </xs:simpleType></xs:element>
                                <xs:element  name="foliage_density"><xs:simpleType> <xs:restriction base="xs:string"> <xs:enumeration value="Low"/> <xs:enumeration value="Medium"/> <xs:enumeration value="High"/> </xs:restriction> </xs:simpleType></xs:element>
                                <xs:element  name="draw_distance"><xs:simpleType> <xs:restriction base="xs:string"> <xs:enumeration value="Low"/> <xs:enumeration value="Medium"/> <xs:enumeration value="High"/> </xs:restriction> </xs:simpleType></xs:element>
                                <xs:element  name="anti_aliasing"><xs:simpleType> <xs:restriction base="xs:string"> <xs:enumeration value="FXAA"/> <xs:enumeration value="MXAA"/> <xs:enumeration value="disabled"/> </xs:restriction> </xs:simpleType></xs:element>
                                <xs:element  name="anisotropic_filtering"><xs:simpleType> <xs:restriction base="xs:string"> <xs:enumeration value="32x"/> <xs:enumeration value="8x"/> <xs:enumeration value="16x"/> </xs:restriction> </xs:simpleType></xs:element>
                                <xs:element name="transparency">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute type="xs:string" name="enabled" use="optional"/>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="tessalation">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute type="xs:string" name="enabled" use="optional"/>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="tracks" minOccurs="0">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute type="xs:string" name="enable"/>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="sound">
                            <xs:complexType>
                              <xs:sequence>
                                  <xs:element  name="general">
                                      <xs:simpleType>
                                          <xs:restriction base="xs:integer"><xs:minInclusive value="0"/><xs:maxInclusive value="100"/></xs:restriction>
                                      </xs:simpleType>
                                  </xs:element>
                                <xs:element  name="vehicle" minOccurs="0"><xs:simpleType>
                                          <xs:restriction base="xs:integer"><xs:minInclusive value="0"/><xs:maxInclusive value="100"/></xs:restriction>
                                      </xs:simpleType>
                                  </xs:element>
                                <xs:element  name="ship" minOccurs="0"><xs:simpleType>
                                          <xs:restriction base="xs:integer"><xs:minInclusive value="0"/><xs:maxInclusive value="100"/></xs:restriction>
                                      </xs:simpleType>
                                  </xs:element>
                                <xs:element  name="music"><xs:simpleType>
                                          <xs:restriction base="xs:integer"><xs:minInclusive value="0"/><xs:maxInclusive value="100"/></xs:restriction>
                                      </xs:simpleType>
                                  </xs:element>
                                <xs:element type="xs:string" name="notification"/>
                                <xs:element name="config">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute type="xs:float" name="system" use="optional"/>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute type="xs:string" name="enabled" use="optional"/>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="controls">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute type="xs:string" name="default" use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element type="xs:string" name="main_battery" minOccurs="0"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:int" name="id" use="optional"/>
                  <xs:attribute type="xs:string" name="psw_autosave" use="optional"/>
                  <xs:attribute type="xs:short" name="port" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="version" use="optional"/>
            <xs:attribute type="xs:string" name="console" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute type="xs:string" name="client"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== xtump/games/pavel_tuma.xml
<?xml version="1.0" encoding="UTF-8"?>



<games xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd.xsd">
    <game version="0.9.17.1 #388" console="false">
        <title>World of Tanks</title>
        <studio>Wargaming.net</studio>
        <web>https://www.worldoftanks.eu</web>
        <user id="222345" psw_autosave="true" port="2000">
            <email>xpetsv@email.cz</email>
            <psw stars="enabled"></psw>
            <server>EU1</server>
            <settings>
                <general>
                    <spam>Hide</spam>
                    <add_friend>ask</add_friend>
                    <battle_types>Standardní bitva, Střetnutí</battle_types>
                    <battle_save source="/battle/videos">Pouze poslední</battle_save>
                    <advanced_scoope>51x, 60x</advanced_scoope>                
                 
                </general>
                <graphics>
                    <resolution>1920x1080</resolution>
			<mode>Fullscreen</mode>
			<gamma value="33" />
			<brightness value="33" />
			<colorblind_mode enabled="false" />
			<vertical_sync enabled="true" />
                        <triple_buff enabled="true" />
		<texture_quality>High</texture_quality>
		<shadow_quality>High</shadow_quality>
		<terrain_quality>Medium</terrain_quality>
		<water_quality>High</water_quality>
                <post_processing>High</post_processing>
		<foliage_quality>High</foliage_quality>
		<foliage_density>Low</foliage_density>
		<draw_distance>High</draw_distance>
		<anti_aliasing>FXAA</anti_aliasing>
		<anisotropic_filtering>8x</anisotropic_filtering>
                <transparency enabled="true" />
		<tessalation enabled="true" />
                <tracks enable="true" />
                </graphics>
                <sound enabled="true">
                    <general>100</general>
                    <vehicle>100</vehicle>
                    <music>75</music>
                    <notification>national</notification>
                    <config system="5.1"/>
                </sound>
                <controls default="true"/>
            </settings>
        </user>
      
    </game>
    <game version="0.6.4" console="false">
        <title>World of Warships</title>
        <studio>Wargaming.net</studio>
        <web>https://www.worldoftanks.eu</web>
        <user id="5524" psw_autosave="true" port="3001">
            <email>warlord@email.cz</email>
            <psw stars="enabled"></psw>
            <server>EU2</server>
            <settings>
                <general>
                    <spam>Show</spam>
                    <add_friend>ask</add_friend>
                    <battle_types>Standardní bitva</battle_types>
                    <battle_save source="/battle/videos">Všechny bitvy</battle_save>
                    <advanced_scoope>21x</advanced_scoope>                
                 
                </general>
                <graphics>
                    <resolution>3840 × 2160</resolution>
			<mode>Fullscreen</mode>
			<gamma value="22" />
			<brightness value="50" />
			<colorblind_mode enabled="false" />
			<vertical_sync enabled="true" />
                        <triple_buff enabled="true" />
		<texture_quality>High</texture_quality>
		<shadow_quality>High</shadow_quality>
		<terrain_quality>High</terrain_quality>
		<water_quality>High</water_quality>
                <post_processing>High</post_processing>
		<foliage_quality>High</foliage_quality>
		<foliage_density>High</foliage_density>
		<draw_distance>High</draw_distance>
		<anti_aliasing>FXAA</anti_aliasing>
		<anisotropic_filtering>32x</anisotropic_filtering>
                <transparency enabled="true" />
		<tessalation enabled="true" />
                </graphics>
                <sound enabled="true">
                    <general>100</general>
                    <ship>100</ship>
                    <music>75</music>
                    <notification>Systémový jazyk</notification>
                    <config system="5.1"/>
                </sound>
                <controls default="false"/>
                <main_battery>Mouse_4</main_battery>
            </settings>
        </user>
    </game>
</games>
